#!/bin/sh

. autofunc

banner=src/qt_install.pri

if [ -f `pwd`/$banner ]; then
    THISPROOT=`pwd`
fi
while [ ! -f `pwd`/$banner ]; do
    cd ..
    if [ "`pwd`" = "/" ]; then
        break;
    fi
    if [ -f `pwd`/$banner ]; then
        THISPROOT=`pwd`
        break;
    fi
done
if [ "`pwd`" != "$THISPATH" ]; then
    cd $THISPATH
fi
[ -z "$THISPROOT" ] && THISPROOT=$THISPATH

# PATH is defined in the head file

func_help_this(){
cat <<-EOF >&2

copyright 2010, all rights reserved.
usage: ${0##*/} [ -h ]
    -h this help

example: ${0##*/} -h
EOF
}

if [ "`pwd`" != "$THISPROOT" ]; then
    cd $THISPROOT
    THISPATH=`pwd`
    THISDIR=`pwd | sed 's:.*/\(.*\):\1:'`
fi
while [ $# -gt 0 ];do
    case $1 in
    --help|-h)
        func_help_this
        exit 0
        ;;
    *)
        echo unknown command $1
	exit 0
	break;
        ;;
    esac
    shift
done
TOOLCHAIN_PATH=$THISC2/c2/daily-jazz2/bin
QT_INSTALL_DIR=$THISC2/Trolltech/QtopiaCore-4.6.1-generic
QT_EXTRA_CONFIG=-plugin-gfx-directfb
C2_DEVTOOLS_PATH=$TOOLCHAIN_PATH/.. ./configure -embedded c2 \
                -little-endian \
                -qt-kbd-linuxinput \
                -qt-libpng \
                -qt-gif \
                -release \
                -prefix $QT_INSTALL_DIR \
                -confirm-license \
                -opensource \
                -qt-libjpeg \
                -qt-libmng \
                -qvfb \
                -depths 8,16,32 \
                -largefile \
                -webkit \
                -svg \
                -xmlpatterns \
                -exceptions \
                -dbus \
                -ldbus-1 \
                $QT_EXTRA_CONFIG \
                -no-rpath \
                -R/c2/local/Trolltech/QtopiaCore-4.6.1-generic/lib
#remove -j5 from make ... -j5, -j5 (multi-thread build)  will lead the depend error for qt.
make C2_DEVTOOLS_PATH=$TOOLCHAIN_PATH/..
make C2_DEVTOOLS_PATH=$TOOLCHAIN_PATH/.. install

