#!/bin/sh


if [ $# -lt 2 ]; then
    echo help of c folder diff
    echo cdiff path1 path2 [sub folder shared by path1 path2]
    exit 0
fi

src1=$1
src2=$2
if [ "$3" != "" ]; then
    src1=$1/$3
    src2=$2/$3
fi

meld  $src1 $src2
# drivers/ /home/hguo/sdk/build/kernel/linux-2.6.29-cvs/drivers/
