#!/bin/sh

. ~/.bash_profile

CONFIG_SCRIPT=`readlink -f $0`
top=${CONFIG_SCRIPT%/*}
if [ -t 1 -o -t 2 ]; then
CONFIG_TTY=y
#[ "${0:0:2}" = "./" ] && top=`pwd`
fi
cd $top

[ -d ~/ymir/bin ] && export PATH=~/ymir/bin:$PATH
log=$top/mirror-sync.log

tm_startdate=`date`
tm_start=`date +%s`

echo `date` start $top/c2sdk >>$log
mkdir -p $top/c2sdk
cd $top/c2sdk
if [ ! -d .repo/repo ]; then
    mkdir -p .repo;
    cd .repo;
    git clone ssh://git.bj.c2micro.com/c2sdk/repo.git;
    cd ..;
fi

if [ ! -d .repo/manifests ]; then
    .repo/repo/repo init --mirror -u ssh://git.bj.c2micro.com/c2sdk/manifests.git -m allgits.xml
else
    .repo/repo/repo sync >>$log 2>&1
fi

echo `date` start $top/android >>$log
mkdir -p $top/android
cd $top/android
if [ ! -d .repo/repo ]; then
    mkdir -p .repo;
    cd .repo;
    git clone ssh://git.bj.c2micro.com/mentor-mirror/build/repo.git;
    cd ..;
fi

if [ ! -d .repo/manifests ]; then
    .repo/repo/repo init --mirror -u ssh://git.bj.c2micro.com/mentor-mirror/build/manifests.git -b devel
else
    .repo/repo/repo sync  >>$log 2>&1
fi


cd $top
tm_done=`date +%s`
echo "`date` mirror sync c2sdk, android $((tm_done-tm_start)) seconds consumed." >>$log
echo "`whoami`@`hostname`:`readlink -f $0`" >>$log
echo "" >>$log
echo "" >>$log
n=`sed -n $= $log`
if [ $n -gt 20000 ];then
  t=$((n-10000))
  sed -i "1,$t d" $log
fi
