#!/bin/sh

. ~/.bash_profile

tm_startdate=`date`
tm_start=`date +%s`
export PATH=~/ymir/bin:$PATH

log=/db/cvsroot/c2-mirror/mirror-sync.log
echo `date` Start $script >>$log

top=/db/cvsroot/c2-mirror/c2sdk
mkdir -p $top
cd $top

if [ ! -d .repo/repo ]; then
    mkdir -p .repo;
    cd .repo;
    git clone ssh://git.bj.c2micro.com/c2sdk/repo.git;
    cd ..;
fi

if [ ! -d .repo/manifests ]; then
    .repo/repo/repo init --mirror -u ssh://git.bj.c2micro.com/c2sdk/manifests.git -m allgits.xml
else
    .repo/repo/repo sync >>$log 2>&1
fi

top=/db/cvsroot/c2-mirror/android
mkdir -p $top
cd $top

if [ ! -d .repo/repo ]; then
    mkdir -p .repo;
    cd .repo;
    git clone ssh://git.bj.c2micro.com/mentor-mirror/build/repo.git;
    cd ..;
fi

if [ ! -d .repo/manifests ]; then
    .repo/repo/repo init --mirror -u ssh://git.bj.c2micro.com/mentor-mirror/build/manifests.git -b devel
else
    .repo/repo/repo sync  >>$log 2>&1
fi


cd /db/cvsroot/c2-mirror
tm_done=`date +%s`
echo "$tm_startdate  ==> `date` : mirror sync c2sdk, android $((tm_done-tm_start)) seconds consumed." >>$log
echo "`whoami`@`hostname`:`readlink -f $0`" >>$log
echo "" >>$log
echo "" >>$log
n=`sed -n $= $log`
if [ $n -gt 20000 ];then
  t=$((n-10000))
  sed -i "1,$t d" $log
fi
