#!/bin/sh

#yum install cvsps first.

c2sdk=/home/hguo/cvs2git
jobtimeout=300000 
mkdir -p ${c2sdk}
cd ${c2sdk}
#checklock

lock=job.lock
if [ -f $lock ]; then
burn=`stat -c%Z $lock`
now=`date +%s`
age=$((now-burn))

#24 Hour = 86400 seconds = 24 * 60 * 60 seconds.
if [ $age -gt $jobtimeout ]; then
    rm -rf $lock
else
    echo An active task `cat $lock` is running for $age seconds, close it before restart.
    exit 1
fi
fi
echo "`readlink -f $0` on $(whoami)@$(hostname) `date`" >$lock

CVSROOT=:pserver:hguo@cvs.c2micro.com:/cvsroot

sdklist="
projects/sw/devtools/3rdParty  
projects/sw/devtools/GNU  
projects/sw/devtools/binutils
projects/sw/devtools/buildroot  
projects/sw/devtools/gcc  
projects/sw/devtools/gcc-4.3.5  
projects/sw/devtools/gdb  
projects/sw/devtools/glibc  
projects/sw/devtools/grouper  
projects/sw/devtools/spimprof  
projects/sw/devtools/termcap  
projects/sw/devtools/uClibc  
projects/sw/devtools/uClibc-0.9.28
projects/sw/cmd/busybox-1.5.1
projects/sw/cmd/busybox-1.13.3
projects/sw/cmd/i2c-tools 
projects/sw/oprofile
projects/sw/directfb/DirectFB-1.4.5
"

sdklist_kernel="
projects/sw/sdk
projects/sw/kernel
projects/sw/prom/u-boot-1.3.0
"

log=`pwd`/log
logp=`pwd`/log.progress

for i in $sdklist; do
    echo "`date` Sync " $i  >>$logp 2>&1
    echo "`date` Sync " $i  >>$log  2>&1
    git cvsimport -v -d $CVSROOT -C ${i##*/} $i >>$log 2>&1

    if [ ! -d ${i##*/}.git ]; then
    if [ "`git --version`" == "git version 1.7.4.1" ]; then
        git clone --bare ${i##*/}
    fi
    fi
done

echo "`date` Sync " all done. >>$logp 2>&1
echo "`date` Sync " all done. >>$log  2>&1

rm -rf $lock
