#!/bin/sh

#yum install cvsps first.

cd /home-localuser/hguo/c2sdk
#checklock

lock=job.lock
if [ -f $lock ]; then
burn=`stat -c%Z $lock`
now=`date +%s`
age=$((now-burn))

#24 Hour = 86400 seconds = 24 * 60 * 60 seconds.
if [ $age -gt 86400 ]; then
    rm -rf $lock
else
    echo An active task `cat $lock` is running for $age seconds, close it before restart.
    exit 1
fi
fi
echo "`readlink -f $0` on $(whoami)@$(hostname) `date`" >$lock

log=`pwd`/log
joblog=job.log
echo "`date` Sync " projects/sw/sdk  >$joblog 2>&1
echo "`date` Sync " projects/sw/sdk >>$log 2>&1
git cvsimport -v -d :pserver:hguo@cvs.c2micro.com:/cvsroot -C sdk     projects/sw/sdk >>$log 2>&1
echo "`date` Sync " projects/sw/kernel >>$joblog 2>&1
echo "`date` Sync " projects/sw/kernel >>$log 2>&1
git cvsimport -v -d :pserver:hguo@cvs.c2micro.com:/cvsroot -C kernel  projects/sw/kernel >>$log 2>&1
echo "`date` Sync " projects/sw/prom/u-boot-1.3.0 >>$joblog 2>&1
echo "`date` Sync " projects/sw/prom/u-boot-1.3.0 >>$log 2>&1
git cvsimport -v -d :pserver:hguo@cvs.c2micro.com:/cvsroot -C u-boot-1.3.0  projects/sw/prom/u-boot-1.3.0 >>$log 2>&1

echo "`date` Sync " all done. >>$joblog 2>&1
echo "`date` Sync " all done. >>$log 2>&1
rm -rf $lock
