#!/bin/sh

#yum install cvsps first.

c2sdk=${1:-`pwd`}
jobtimeout=${2:-864000}

cd ${c2sdk}
#checklock

lock=job.lock
if [ -f $lock ]; then
burn=`stat -c%Z $lock`
now=`date +%s`
age=$((now-burn))

#24 Hour = 86400 seconds = 24 * 60 * 60 seconds.
if [ $age -gt $jobtimeout ]; then
    rm -rf $lock
else
    echo An active task `cat $lock` is running for $age seconds, close it before restart.
    exit 1
fi
fi
echo "`readlink -f $0` on $(whoami)@$(hostname) `date`" >$lock

CVSROOT=:pserver:hguo@cvs.c2micro.com:/cvsroot
sdklist="
projects/sw/sdk
projects/sw/kernel
projects/sw/prom/u-boot-1.3.0
"

log=`pwd`/log
logp=`pwd`/log.progress

for i in $sdklist; do
    echo "`date` Sync " $i  >>$logp 2>&1
    echo "`date` Sync " $i  >>$log  2>&1
    git cvsimport -v -d $CVSROOT -C ${i##*/} $i >>$log 2>&1
done

echo "`date` Sync " all done. >>$logp 2>&1
echo "`date` Sync " all done. >>$log  2>&1

rm -rf $lock
