#!/bin/sh

#yum install cvsps first.

c2sdk=/home/hguo/cvs2git
jobtimeout=300000 

cd ${c2sdk}
#checklock

lock=job.lock
if [ -f $lock ]; then
    burn=`stat -c%Z $lock`
    now=`date +%s`
    age=$((now-burn))
    
    #24 Hour = 86400 seconds = 24 * 60 * 60 seconds.
    if [ $age -gt $jobtimeout ]; then
        rm -rf $lock
    else
        echo An active task `cat $lock` is running for $age seconds, close it before restart.
        exit 1
    fi
fi
echo "`readlink -f $0` on $(whoami)@$(hostname) `date`" >$lock

CVSROOT=:pserver:hguo@cvs.c2micro.com:/cvsroot

#log=`pwd`/log#-`date +%Y%m%d%H%M%S`
log=`pwd`/log
logp=$log.progress

cvs2git_module()
{
    #$1 is cvs module name
    #$2 is git module name
    echo "`date` Scan cvs module $1 to git $2"  >>$logp 2>&1
    echo "`date` Scan cvs module $1 to git $2"  >>$log  2>&1

    UPDATE_FLAGS=
    GITCMD="git cvsimport -v -a -k -d $CVSROOT $UPDATE_FLAGS -C $2 $1";
    echo "`date` $GITCMD"   >>$log 2>&1;
    $GITCMD >>$log 2>&1

    echo "`date` Scan cvs module $1 to git $2 done."  >>$logp 2>&1
    echo "`date` Scan cvs module $1 to git $2 done."  >>$log  2>&1
}

#manually clean(rm -rf) the target folder first

kernel_parts="
1gb.part  4gb.part  8gb.part           initramfs_files      loadk_proto.scr  merge-tools  nmp-nand.mk
2gb.part  512.part  configs   hd.part  initramfs_source.in  Makefile         nmp1.mk      nmp-spi.mk
"
for i in $kernel_parts ; do
    cvs2git_module    projects/sw/kernel/$i  kernel-misc
done

cvs2git_module    projects/sw/kernel/linux-2.6     linux-2.6.23
#cvs2git_module    projects/sw/kernel/linux-2.6.14  linux-2.6.14
#cvs2git_module    projects/sw/kernel/linux-2.6.29  linux-2.6.29
#cvs2git_module    projects/sw/kernel/linux-2.6.32  linux-2.6.32

echo "`date` Sync " all done. >>$logp 2>&1
echo "`date` Sync " all done. >>$log  2>&1

rm -rf $lock
