#!/bin/sh

list="
projects/sw/sdk/configs
projects/sw/sdk/automation
"


[ $CVSROOT ] || export CVSROOT=/db/cvsroot
REPODIR=${1:-$HOME/maintreetag}
CVSDIR=$REPODIR/cvs
mkdir -p $REPODIR $CVSDIR
[ -d $REPODIR ] || exit 0
cd $REPODIR
if [ -f sdk_content ];then
    list="`cat sdk_content`"
fi
logupd=$REPODIR/log.update
logcvs=$REPODIR/log.cvs
lognew=$REPODIR/log.new
logall=$REPODIR/log.log
>$logupd
>$lognew
for i in $list;do
    idotgit=$REPODIR/${i##*/}.git
    pushd $CVSDIR
    echo "Checkout $i"
    cvs -q co $i >>$logcvs
    pushd $i
    if [ -d .git ];then 
        clean=$(git status | grep "nothing to commit (working directory clean)")
        if [ "$clean" == "" ]; then
	    echo "Update git on $i" >>$logupd
            echo "add these to git"
            git status  
            git add .
            git commit -m "commit at $(date)"
            git push $idotgit
        else
            echo "$i : git is clean, does not push."
            echo "$i : git is clean, does not push." >>$logupd
        fi	
    else
	echo "Create git on $i" >>$lognew
	githere
    fi
    popd
    popd
    if [ ! -d $idotgit ];then
        git clone --bare $CVSDIR/$i
        if [ ! -d  $idotgit -a -d ${i##*/} ];then
            mv ${i##*/} $idotgit
        fi
	echo "Create bare git on $idotgit" >>$lognew
    else
        echo "found bare git $idotgit for $i" >>$lognew
    fi
done
cat $lognew >>$logall
cat $logupd >>$logall
echo "Done on `date`" >>$logall
echo "Done on `date`" >>$lognew
echo "Done on `date`" >>$logupd
repohere
