#!/bin/sh

[ -d .git ] && exit 0

[ -f .gitignore ] || (
cat <<endofcat  >.gitignore
#autocreated file on `hostname` by `whoami`, `date`"
*.o
*.d
*.out
*.map
*.cmd
*.bin
.#*
.tmp*
.config*
..tmp*
cscope*
CVS
CVSROOT
Entries  
Entries.Log  
Repository  
Root
Tag
.version
vmlinux*
zvmlinux*
.pc
GPATH
GRTAGS
GSYMS
GTAGS
patches
endofcat
) 
git init
git add .
git commit -m "git init repo on `hostname` by `whoami`, `date`"

