#!/bin/sh

remote=`git remote`
branch=`git branch | grep ^\* |sed 's,\* \(.*\),\1,g'`
pulled=
echo Git at $remote  $branch

if [ "$remote" != "" ];then
if [ "$branch" != "" ];then
    git pull $remote $branch
    pulled=1
fi
fi

if [ "$pulled" == "" ];then
    echo Pul nothing
fi
