#!/bin/sh

if [ $# -lt 3 ]; then
cat <<ENDOFHELP
    multi source to multi destination copy
    ${0##*/} srcpath dstpath  pathfile1...

    example ${0##*/} ../old  .  f1 f2/f3
    will execute:
    "    cp -rf ../old/f1 ./f1"
    "    cp -rf ../old/f2/f3 ./f2/f3"
ENDOFHELP
    exit 0
fi

src=$1
dst=$2
shift 2
while [ $# -gt 0 ];do
    echo cp -rf $src/$1 $dst/$1
    cp -rf $src/$1 $dst/$1
    shift
done

