# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# # This file is built by mktables from e.g. UnicodeData.txt.
# # Any changes made here will be lost!

our %known_tasks = (
	'projx' => {
		'title'   => 'CTS daily test report',
		'config'  => 'your test configuration info for human',
                'hostip'  => '10.16.6.204',
		'user'    => 'hguo',
		'home'	  => '/home/meanmi/DailyTest_Result',
		'script'  => '/usr/bin/clear',
		'reset'   => 'manual',
                'clientip'=> '10.16.6.88',
		'status'  => 'on',
		},
	'projy' => {
		'title'   => 'Script test case, for 3 fields ^cate:res:log',
		'config'  => 'your test configuration info for human',
                'hostip'  => '10.16.6.204',
		'user'    => 'hguo',
		'home'	  => '/home/hguo/out3',
		'script'  => '/usr/bin/clear',
		'reset'   => 'manual',
                'clientip'=> '10.16.6.88',
		'status'  => 'on',
		},
	'projz' => {
		'title'   => 'Script test case, for 4 fields ^cate:sub:res:log',
		'config'  => 'your test configuration info for human',
                'hostip'  => '10.16.6.204',
		'user'    => 'hguo',
		'home'	  => '/home/hguo/out',
		'script'  => '/usr/bin/clear',
		'reset'   => 'manual',
                'clientip'=> '10.16.6.88',
		'status'  => 'on',
		},
);
