#!/bin/sh

top=`pwd`
host=`hostname`
server=$host
remote=c2git
manifest=$top/manifests/default.xml
  
[ -d manifests.git ] && exit 0
  
mkdir -p  manifests
cat <<EOTEXT >manifests/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote  name="$remote" 
           fetch="ssh://${server}${top}" />
  <default revision="master" remote="$remote" />

  <project path="manifests" name="manifests"  />

EOTEXT

searchgit=`find . -maxdepth 1 -name \*.git -type d`
for i in $searchgit;do
    idotgit=${i##*/}
    echo "  <project path=\"${idotgit%.git}\" name=\"${idotgit%.git}\" />" >>$manifest
done
echo "" >>$manifest
echo "</manifest>" >>$manifest

cat <<EOTEXT >$top/manifests/README
#!/bin/sh
repo init -u ssh://${server}${top}/manifests.git 
repo sync
repo start --all master
EOTEXT

cd manifests
githere
cd $top

git clone --bare manifests
#let group can access it
chmod -R g+w manifests.git

if [ -t 1 -o -t 2 ];then
    cat $top/manifests/README
fi
cp $top/manifests/README README.repo

rm -rf manifests 
