#!/bin/sh
##  cron debug message code, these setting does not pass to Makefile
#----------------------------------------------------------------------
#export MISSION=`echo $0 | sed 's:.*/\(.*\):\1:'`
export MISSION=${0##*/}
export rlog=$HOME/rlog/rlog.$MISSION
mkdir -p $HOME/rlog
recho()
{
    #progress echo, for debug during run as the crontab task.
    if [ ! -z "$rlog" ] ; then
    echo `date +"%Y-%m-%d %H:%M:%S"` " $@" >>$rlog.log.txt
    fi
    echo `date +"%Y-%m-%d %H:%M:%S"` " $@"
}
recho_time_consumed()
{
    tm_b=`date +%s`
    tm_c=$(($tm_b-$1))
    tm_h=$(($tm_c/3600))
    tm_m=$(($tm_c/60))
    tm_m=$(($tm_m%60))
    tm_s=$(($tm_c%60))
    shift
    recho "$@" "$tm_c seconds / $tm_h:$tm_m:$tm_s consumed."
}

repodir=/mentor-mirror/build
tmpfile=/tmp/${0##*/}-$$

recho "This will do 'repo rebase' for a specified module"

gmodule=$1
gname=${gmodule##*/}
gname=${gname%.git}
if [ ! -d $gmodule ];then
    echo Fail on:
    echo "    can not found module $gmodule"
    exit 0
fi

mkdir -p /tmp/$USER
cd /tmp/$USER
rm -rf ${gname}
git clone $gmodule

if [ ! -d ${gname} ]; then
    echo Fail on:
    echo "    git clone $gmodule"
    echo "    can not found folder $gname"
    exit 0
fi
cd ${gname}
master=$(git branch | grep ^* | sed 's/\* \(.*\)/\1/g')
remote=$(git remote)

echo $gname master=$master, remote=$remote

git checkout devel
#git rebase $master
echo "git merge $master"
git merge $master

echo "Please confirm now can do \"git push $remote devel\", are you want continue now[N/y] ?"
read confirm
if [ "$confirm" == "y" ] ; then
    git push $remote devel
else
    echo "Please merge it manually, then call"
    echo "    git push $remote devel"
fi

