#!/bin/sh

TMPF=/tmp/tmpvi$$
LOGF=$HOME/sdk/worklog

echo `date +"%Y-%m-%d %H:%M:%S"`  >$TMPF
echo ""  >>$TMPF

vi $TMPF +2
cat $LOGF >>$TMPF
cp -f $TMPF $LOGF
cp -f $LOGF /public/    #backup for ref
rm -f $TMPF



